<?xml version="1.0" encoding="utf-8"?><Database Name="myTherapist" Class="OilsUsedDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\myTherapist.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="myTherapistConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.OilsUsed" Member="OilsUseds">
    <Type Name="OilsUsed">
      <Column Name="ApptDate" Type="System.DateTime" DbType="DateTime2 NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="OilsUsed" Member="OilsUsed1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Guid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
</Database>