#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MyTherapist")]
public partial class TherapistsDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  #endregion
	
	public TherapistsDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["MyTherapistConnectionString2"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public TherapistsDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public TherapistsDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public TherapistsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public TherapistsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Therapist> Therapists
	{
		get
		{
			return this.GetTable<Therapist>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Therapists")]
public partial class Therapist
{
	
	private System.Guid _TherapistId;
	
	private string _TherapistName;
	
	public Therapist()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TherapistId", DbType="UniqueIdentifier NOT NULL")]
	public System.Guid TherapistId
	{
		get
		{
			return this._TherapistId;
		}
		set
		{
			if ((this._TherapistId != value))
			{
				this._TherapistId = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TherapistName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string TherapistName
	{
		get
		{
			return this._TherapistName;
		}
		set
		{
			if ((this._TherapistName != value))
			{
				this._TherapistName = value;
			}
		}
	}
}
#pragma warning restore 1591
